# 
# Copyright (C) 2021 NVIDIA Corporation.  All rights reserved.
# Licensed under the NVIDIA Source Code License.
# See LICENSE at https://github.com/nv-tlabs/ATISS.
# Authors: Despoina Paschalidou, Amlan Kar, Maria Shugrina, Karsten Kreis,
#          Andreas Geiger, Sanja Fidler
# 

THREED_FRONT_BEDROOM_FURNITURE = {
    "desk":                                    "desk",
    "nightstand":                              "nightstand",
    "king-size bed":                           "double_bed",
    "double bed":                              "double_bed",
    "single bed":                              "single_bed",
    "kids bed":                                "kids_bed",
    "ceiling lamp":                            "ceiling_lamp",
    "pendant lamp":                            "pendant_lamp",
    "bookcase/jewelry armoire":                "bookshelf",
    "tv stand":                                "tv_stand",
    "wardrobe":                                "wardrobe",
    "lounge chair/cafe chair/office chair":    "chair",
    "dining chair":                            "chair",
    "classic chinese chair":                   "chair",
    "folding chair":                           "chair",
    "hanging chair":                           "chair",
    "lounge chair/book-chair/computer chair":  "chair",
    "armchair":                                "armchair",
    "dressing table":                          "dressing_table",
    "dressing chair":                          "dressing_chair",
    "corner/side table":                       "table",
    "dining table":                            "table",
    "round end table":                         "table",
    "tea table":                               "coffee_table",
    "drawer chest/corner cabinet":             "cabinet",
    "sideboard/side cabinet/console table":    "cabinet",
    "cabinet":                                 "cabinet",
    "wine cabinet":                            "cabinet",
    "children cabinet":                        "children_cabinet",
    "shelf":                                   "shelf",
    "footstool/sofastool/bed end stool/stool": "stool",
    "coffee table":                            "coffee_table",
    "loveseat sofa":                           "sofa",
    "three-seat/multi-seat sofa":              "sofa",
    "l-shaped sofa":                           "sofa",
    "lazy sofa":                               "sofa",
    "chaise longue sofa":                      "sofa",
    "couch bed":                               "sofa",
    "three-seat/multi-person sofa":            "sofa",
    "two-seat sofa":                           "sofa",
    "u-shaped sofa":                           "sofa"
}

THREED_FRONT_LIBRARY_FURNITURE = {
    "bookcase/jewelry armoire":                "bookshelf",
    "desk":                                    "desk",
    "pendant lamp":                            "pendant_lamp",
    "ceiling lamp":                            "ceiling_lamp",
    "lounge chair/cafe chair/office chair":    "chair",
    "lounge chair/book-chair/computer chair":  "chair",
    "dining chair":                            "chair",
    "dining table":                            "table",
    "corner/side table":                       "table",
    "classic chinese chair":                   "chair",
    "armchair":                                "armchair",
    "folding chair":                           "chair",
    "hanging chair":                           "chair",
    "shelf":                                   "shelf",
    "sideboard/side cabinet/console table":    "cabinet",
    "footstool/sofastool/bed end stool/stool": "stool",
    "barstool":                                "stool",
    "round end table":                         "table",
    "tea table":                               "coffee_table",
    "loveseat sofa":                           "sofa",
    "drawer chest/corner cabinet":             "cabinet",
    "cabinet":                                 "cabinet",
    "wardrobe":                                "wardrobe",
    "three-seat/multi-seat sofa":              "sofa",
    "couch bed":                               "sofa",
    "three-seat/multi-person sofa":            "sofa",
    "two-seat sofa":                           "sofa",
    "u-shaped sofa":                           "sofa",
    "wine cabinet":                            "cabinet",
    "coffee table":                            "coffee_table",
    "lazy sofa":                               "sofa",
    "children cabinet":                        "cabinet",
    "chaise longue sofa":                      "sofa",
    "l-shaped sofa":                           "sofa",
    "dressing table":                          "dressing_table",
    "dressing chair":                          "dressing_chair",
}

THREED_FRONT_LIVINGROOM_FURNITURE = {
    "bookcase/jewelry armoire":                "bookshelf",
    "desk":                                    "desk",
    "pendant lamp":                            "pendant_lamp",
    "ceiling lamp":                            "ceiling_lamp",
    "lounge chair/cafe chair/office chair":    "chair",
    "lounge chair/book-chair/computer chair":  "chair",
    "dining chair":                            "chair",
    "dining table":                            "table",
    "corner/side table":                       "table",
    "classic chinese chair":                   "chair",
    "folding chair":                           "chair",
    "hanging chair":                           "chair",
    "armchair":                                "armchair",
    "shelf":                                   "shelf",
    "sideboard/side cabinet/console table":    "cabinet",
    "footstool/sofastool/bed end stool/stool": "stool",
    "barstool":                                "stool",
    "round end table":                         "table",
    "tea table":                               "coffee_table",
    "loveseat sofa":                           "sofa",
    "drawer chest/corner cabinet":             "cabinet",
    "wardrobe":                                "wardrobe",
    "three-seat/multi-seat sofa":              "sofa",
    "couch bed":                               "sofa",
    "three-seat/multi-person sofa":            "sofa",
    "two-seat sofa":                           "sofa",
    "u-shaped sofa":                           "sofa",
    "wine cabinet":                            "cabinet",
    "coffee table":                            "coffee_table",
    "lazy sofa":                               "sofa",
    "children cabinet":                        "cabinet",
    "cabinet":                                 "cabinet",
    "chaise longue sofa":                      "sofa",
    "l-shaped sofa":                           "sofa",
    "tv stand":                                "tv_stand"
}
