site_name: Fast Transformers for PyTorch
repo_url: https://github.com/idiap/fast-transformers
theme: readthedocs
extra_javascript: 
    - https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.0/MathJax.js?config=TeX-AMS-MML_HTMLorMML
extra_css:
    - css/extra.css
markdown_extensions:
    - mdx_math
    - tables
    - admonition
nav:
    - Home: index.md
    - Transformers: transformers.md
    - Masking: masking.md
    - Attention: attention.md
    - Feature Maps: feature_maps.md
    - Builders: builders.md
    - Custom Attention Layer: custom_attention_layer.md
    - Recurrent Transformers: recurrent_transformers.md
    - Events: events.md
    - Tips and Tricks: tips_and_tricks.md
    - API Docs: /api_docs/fast_transformers/
