defaults:
- repro_singleseq_base
- _self_
data_source_args:
  data_loader_map_provider_SequenceDataLoaderMapProvider_args:
    batch_size: 10
    dataset_length_train: 1000
    dataset_length_val: 1
    num_workers: 8
    images_per_seq_options:
    - 2
    - 3
    - 4
    - 5
    - 6
    - 7
    - 8
    - 9
    - 10
